--1 non sub
SELECT
    CUSTOMER_NAME,
    CUSTOMER_CITY,
    CUSTOMER_STREET
FROM
    CUSTOMER
    NATURAL JOIN DEPOSITOR
    NATURAL JOIN ACCOUNT
    NATURAL JOIN BRANCH INTERSECT
    SELECT
        CUSTOMER_NAME,
        BRANCH_CITY,
        CUSTOMER_STREET
    FROM
        CUSTOMER
        NATURAL JOIN DEPOSITOR
        NATURAL JOIN ACCOUNT
        NATURAL JOIN BRANCH;

--1 sub
SELECT
    CUSTOMER_NAME,
    CUSTOMER_STREET,
    CUSTOMER_CITY
FROM
    CUSTOMER  CUS
WHERE
    CUSTOMER_CITY = SOME (
        SELECT
            BRANCH_CITY
        FROM
            BRANCH
            NATURAL JOIN ACCOUNT
            NATURAL JOIN DEPOSITOR
        WHERE
            CUS.CUSTOMER_NAME = DEPOSITOR.CUSTOMER_NAME
    );

--2 non sub
SELECT
    CUSTOMER_NAME,
    CUSTOMER_CITY,
    CUSTOMER_STREET
FROM
    CUSTOMER
    NATURAL JOIN BORROWER
    NATURAL JOIN LOAN NATURAL
    JOIN BRANCH 
INTERSECT
    SELECT
        CUSTOMER_NAME,
        BRANCH_CITY,
        CUSTOMER_STREET
    FROM
        CUSTOMER
        NATURAL JOIN BORROWER
        NATURAL JOIN LOAN
        NATURAL JOIN BRANCH

--2 SUB
SELECT CUSTOMER_NAME, CUSTOMER_STREET, CUSTOMER_CITY
FROM CUSTOMER cus
WHERE cus.CUSTOMER_CITY = SOME(
    SELECT BRANCH_CITY 
    FROM BRANCH NATURAL JOIN BORROWER NATURAL JOIN LOAN
    WHERE cus.CUSTOMER_NAME = BORROWER.CUSTOMER_NAME
)

--3 with
